### ISSUE TITLE
installing sense2vec gives Clang error

### ISSUE THREAD

**Issue by humzaiqbal** [explosion/sense2vec#67] opened 2018-12-26 02:25 UTC
System overview:

- `OS: Mac osX 10.13.6`

- `python: 3.7`

- `numpy: 1.17.0.dev0+05cf88c`

- `preshed: 1.0.1 `

- `cymem: 1.31.2 `

- `spacy: 2.0.12`

- `ujson: 1.35`

- `cython: 0.28`

Hi, I tried installing `sense2vec` using `pip install sense2vec==1.0.0a0` as per the instructions, but found that when I did I got this error `error: command 'clang' failed with exit status 1` followed by 

`Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-1d45muej/sense2vec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-1d3f4e95/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-1d45muej/sense2vec/`.
<img width="1651" alt="clang_screenshot" src="https://user-images.githubusercontent.com/10646338/50429360-cc655e00-0872-11e9-8925-23490281a999.png">

 I looked at the `requirements.txt` as well as the `requirements-dev.txt` to make sure I have the right / compatible versions for all requirements as listed above, but I am still getting errors, any help would be appreciated. Thanks :)

**Comment by tarskiandhutch** [comment] 2019-02-27 17:14
Hello! I have the exact same problem, with pretty much the same system setup (Mac OS 10.14.3). The following might help with debugging. 

After attempting a pip install via `pip install sense2vec==1.0.0a0` and getting the same error messages as @humzaiqbal , spaCy itself _also_ stops working. Here is what happens when I attempt to import spaCy from the Python interpreter afterwards:

```
>>> import spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 8, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/usr/local/lib/python3.7/site-packages/thinc/neural/__init__.py", line 1, in <module>
    from ._classes.model import Model
  File "/usr/local/lib/python3.7/site-packages/thinc/neural/_classes/model.py", line 12, in <module>
    from ..train import Trainer
  File "/usr/local/lib/python3.7/site-packages/thinc/neural/train.py", line 3, in <module>
    from .optimizers import Adam, SGD, linear_decay
  File "optimizers.pyx", line 13, in init thinc.neural.optimizers
  File "cymem.pxd", line 4, in init thinc.neural.ops
AttributeError: module 'cymem.cymem' has no attribute 'PyMalloc'
```

Luckily, this second problem can be solved by exiting the Python interpreter and reinstalling spaCy in the usual way via `pip install -U spacy`.

Good luck! And I hope you get sense2vec back up and running again!

**Comment by nateraw** [comment] 2019-03-13 22:48
I think this is a duplicate of #66 ...are you on Mojave?

**Comment by tarskiandhutch** [comment] 2019-03-14 13:12
@nateraw indeed I am.

**Comment by nateraw** [comment] 2019-03-14 18:48
:sweat: yeah it's all messed up on Mojave.

**Comment by neuhausler** [comment] 2019-05-29 23:46
Anyone having an update on this issue?

**Comment by gitcarbs** [comment] 2019-10-28 01:25
I was able to get past the clang errors by installing sense2vec using the following command on Mojave:

```
CFLAGS=-mmacosx-version-min=10.9 pip install sense2vec==1.0.0a1
```

**Comment by ines** [comment] 2019-10-29 17:51
The upcoming stable version (see #77) was completely refactored from scratch and is now a pure Python module. This should hopefully make installation much simpler 🙂

**Closed as completed by ines** 2019-10-29 17:51 UTC
Labels: install
